blank_issues_enabled: false
contact_links:
  - name: 💬 Me poser une question
    url: mailto:gregoire.favreau@ik.me
    about: Pour toute question qui ne rentre pas dans les templates ci-dessus.
  - name: 🔗 Tous mes liens
    url: https://linktr.ee/gregoiref
    about: Linktree, Ko-fi, LinkedIn et plus.
