name: 📝 Lint

on:
  push:
    branches: [main]
    paths:
      - "README.md"
      - "NOW.md"
      - ".markdownlint.json"
      - ".github/**"
  pull_request:
    paths:
      - "README.md"
      - "NOW.md"
      - ".markdownlint.json"
      - ".github/**"

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    name: Markdown lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔍 Lint README & NOW
        uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          globs: |
            README.md
            NOW.md
          config: ".markdownlint.json"

  lint-yaml:
    name: YAML lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: 🔍 Lint workflows YAML
        run: |
          pip install yamllint --quiet
          yamllint -d "{extends: relaxed, rules: {line-length: {max: 200}}}" \
            .github/workflows/
